-- Row Level Security hardening for EyeQ AI.
--
-- All application access goes through the Next.js server using Prisma,
-- which connects as the table owner and is not affected by these policies.
-- Enabling RLS with no permissive policies denies all direct access through
-- the Supabase Data API (anon and authenticated roles), so patient data can
-- only be reached through the server, which enforces organization and role
-- checks in code.
--
-- Apply with:
--   npx dotenv -e .env.local -- prisma db execute --file prisma/rls.sql --schema prisma/schema.prisma

ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Location" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserLocationAccess" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Provider" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Patient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Appointment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImagingCase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImagingAsset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImageQualityAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImagingAnalysis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImagingFinding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProviderImagingReview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModelRegistry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImagingAuditEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClinicalNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Prescription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareGap" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageThread" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Document" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EhrIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EhrSyncLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DiseaseTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AmbientScribeSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiAssistantConversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiAssistantMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TranscriptSegment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReminderTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReminderCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CommunicationPreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageDeliveryLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TranslationString" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FinancialReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientForm" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiGatewayRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiGatewayResponse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiProviderConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiModelRoute" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiUsageRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PhiDetectionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BlockedAiRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiKnowledgeDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiKnowledgeChunk" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Encounter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffTask" ENABLE ROW LEVEL SECURITY;

-- Pilot / live PHI additions (deny-by-default for anon/authenticated Data API)
ALTER TABLE "ExamChart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Claim" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RemittanceAdvice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientStatement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OpticalOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OpticalLab" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AppointmentRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentLedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StripeWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GoogleBusinessConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GoogleReview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MigrationProject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VisitWorkflowTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientMergeRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BackgroundJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VendorReadiness" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PatientProxyAccess" ENABLE ROW LEVEL SECURITY;

-- Force RLS so table owner bypass cannot be relied on for direct SQL roles.
-- Application Prisma connections typically use the table owner; keep app-layer
-- organizationId checks as the primary tenant control. These policies deny
-- PostgREST anon/authenticated paths.
ALTER TABLE "Patient" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Appointment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Encounter" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ClinicalNote" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Prescription" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ImagingCase" FORCE ROW LEVEL SECURITY;
ALTER TABLE "MessageThread" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Message" FORCE ROW LEVEL SECURITY;
ALTER TABLE "PatientInvoice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Claim" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AppointmentRequest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CareGap" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiGatewayRequest" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
ALTER TABLE "InventoryItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "OpticalOrder" FORCE ROW LEVEL SECURITY;
