import React from 'react';
import { Img, staticFile } from 'remotion';
import { theme } from '../theme';

const SHOT_FILES: Record<string, string> = {
  hero: 'screenshots/hero.png',
  dashboard: 'screenshots/dashboard.png',
  'patient-chart': 'screenshots/patient-chart.png',
  'imaging-review': 'screenshots/imaging-review.png',
  'rx-optical': 'screenshots/rx-optical.png',
  'ai-copilot': 'screenshots/ai-copilot.png',
  'patient-portal': 'screenshots/patient-portal.png',
  business: 'screenshots/business.png',
  'phi-readiness': 'screenshots/phi-readiness.png',
  cta: 'screenshots/cta.png',
};

/** Always show product images (generated by `npm run assets`). */
export const ScreenshotOrMock: React.FC<{
  shot?: string;
  children: React.ReactNode;
  style?: React.CSSProperties;
}> = ({ shot, children, style }) => {
  const rel = shot ? SHOT_FILES[shot] ?? `screenshots/${shot}.png` : null;

  if (rel) {
    return (
      <div
        style={{
          borderRadius: 18,
          overflow: 'hidden',
          border: `1px solid ${theme.glassBorder}`,
          boxShadow: theme.shadow,
          background: theme.glassStrong,
          ...style,
        }}
      >
        <Img
          src={staticFile(rel)}
          style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
        />
      </div>
    );
  }

  return <div style={style}>{children}</div>;
};
